### ISSUE TITLE
cb/index-path indexes backup files

### ISSUE THREAD

**Issue by Flawless** [thheller/shadow-css#14]
I spent some time trying to figure out why I couldn't get valid CSS files after the initial build, as described in the README. Eventually, I discovered that the files were only being generated correctly after the file watcher triggered on the exact file. I think it's important to note that the index-patch function uses the `str/index-of` function to detect all Clojure files, which means it also grabs any files that have additional symbols after the extension, such as default Emacs backups.

Although replacing index-of with regex matching would lead to an increase in the time taken to index files, I believe this behavior should still be noted so that others won't make the same mistake as me.

**Comment by thheller** [comment]
Just forgot to filter hidden files. Should be taken care of in master. Do you use deps.edn or the regular maven release? I can make a quick release if it helps.
