### ISSUE TITLE
Keyframe workaround

### ISSUE THREAD

**Issue by jeans11** [thheller/shadow-css#21]
Hi!

I'm wonder what if the workaround to deals with the keyframes. Just create a css file and add it into the `index.html`? or there is a better way?

Thanks

**Comment by thheller** [comment]
You can include arbitrary .css files via the `:shadow.css/include` directive in one of your CLJS `ns` forms.

See [here](https://github.com/thheller/shadow-cljs/blob/c817ccebedc785c0ee93743f646cda93095c9e20/src/main/shadow/cljs/ui/components/code_editor.cljs#L2)

```
(ns shadow.cljs.ui.components.code-editor
  {:shadow.css/include ["shadow/cljs/ui/components/code-editor.css"]}
  ...)
```

This will cause the build process to include [the linked css file](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/ui/components/code-editor.css) in the final output.

This is just a regular CSS file, no processing of any kind is done. An extra CSS file linked via HTML of course also works.

**Comment by jeans11** [comment]
Thanks @thheller!
